/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace Echo.ThriftModel
{
  public static class echoExtensions
  {
    public static bool Equals(this Dictionary<string, global::Echo.ThriftModel.BusinessDocument> instance, object that)
    {
      if (!(that is Dictionary<string, global::Echo.ThriftModel.BusinessDocument> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, global::Echo.ThriftModel.BusinessDocument> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static Dictionary<string, global::Echo.ThriftModel.BusinessDocument> DeepCopy(this Dictionary<string, global::Echo.ThriftModel.BusinessDocument> source)
    {
      if (source == null)
        return null;

      var tmp232 = new Dictionary<string, global::Echo.ThriftModel.BusinessDocument>(source.Count);
      foreach (var pair in source)
        tmp232.Add((pair.Key != null) ? pair.Key : null, (pair.Value != null) ? pair.Value.DeepCopy() : null);
      return tmp232;
    }


    public static bool Equals(this Dictionary<string, global::Echo.ThriftModel.Variant> instance, object that)
    {
      if (!(that is Dictionary<string, global::Echo.ThriftModel.Variant> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this Dictionary<string, global::Echo.ThriftModel.Variant> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static Dictionary<string, global::Echo.ThriftModel.Variant> DeepCopy(this Dictionary<string, global::Echo.ThriftModel.Variant> source)
    {
      if (source == null)
        return null;

      var tmp233 = new Dictionary<string, global::Echo.ThriftModel.Variant>(source.Count);
      foreach (var pair in source)
        tmp233.Add((pair.Key != null) ? pair.Key : null, (pair.Value != null) ? pair.Value.DeepCopy() : null);
      return tmp233;
    }


    public static bool Equals(this List<global::Echo.ThriftModel.Attachment> instance, object that)
    {
      if (!(that is List<global::Echo.ThriftModel.Attachment> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Echo.ThriftModel.Attachment> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::Echo.ThriftModel.Attachment> DeepCopy(this List<global::Echo.ThriftModel.Attachment> source)
    {
      if (source == null)
        return null;

      var tmp234 = new List<global::Echo.ThriftModel.Attachment>(source.Count);
      foreach (var elem in source)
        tmp234.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp234;
    }


    public static bool Equals(this List<global::Echo.ThriftModel.BusinessDocument> instance, object that)
    {
      if (!(that is List<global::Echo.ThriftModel.BusinessDocument> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Echo.ThriftModel.BusinessDocument> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::Echo.ThriftModel.BusinessDocument> DeepCopy(this List<global::Echo.ThriftModel.BusinessDocument> source)
    {
      if (source == null)
        return null;

      var tmp235 = new List<global::Echo.ThriftModel.BusinessDocument>(source.Count);
      foreach (var elem in source)
        tmp235.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp235;
    }


    public static bool Equals(this List<global::Echo.ThriftModel.DocType> instance, object that)
    {
      if (!(that is List<global::Echo.ThriftModel.DocType> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Echo.ThriftModel.DocType> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::Echo.ThriftModel.DocType> DeepCopy(this List<global::Echo.ThriftModel.DocType> source)
    {
      if (source == null)
        return null;

      var tmp236 = new List<global::Echo.ThriftModel.DocType>(source.Count);
      foreach (var elem in source)
        tmp236.Add(elem);
      return tmp236;
    }


    public static bool Equals(this List<global::Echo.ThriftModel.LineItem> instance, object that)
    {
      if (!(that is List<global::Echo.ThriftModel.LineItem> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Echo.ThriftModel.LineItem> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::Echo.ThriftModel.LineItem> DeepCopy(this List<global::Echo.ThriftModel.LineItem> source)
    {
      if (source == null)
        return null;

      var tmp237 = new List<global::Echo.ThriftModel.LineItem>(source.Count);
      foreach (var elem in source)
        tmp237.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp237;
    }


    public static bool Equals(this List<global::Echo.ThriftModel.Payment> instance, object that)
    {
      if (!(that is List<global::Echo.ThriftModel.Payment> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::Echo.ThriftModel.Payment> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::Echo.ThriftModel.Payment> DeepCopy(this List<global::Echo.ThriftModel.Payment> source)
    {
      if (source == null)
        return null;

      var tmp238 = new List<global::Echo.ThriftModel.Payment>(source.Count);
      foreach (var elem in source)
        tmp238.Add((elem != null) ? elem.DeepCopy() : null);
      return tmp238;
    }


    public static bool Equals(this List<int> instance, object that)
    {
      if (!(that is List<int> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<int> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<int> DeepCopy(this List<int> source)
    {
      if (source == null)
        return null;

      var tmp239 = new List<int>(source.Count);
      foreach (var elem in source)
        tmp239.Add(elem);
      return tmp239;
    }


    public static bool Equals(this List<string> instance, object that)
    {
      if (!(that is List<string> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<string> DeepCopy(this List<string> source)
    {
      if (source == null)
        return null;

      var tmp240 = new List<string>(source.Count);
      foreach (var elem in source)
        tmp240.Add((elem != null) ? elem : null);
      return tmp240;
    }


  }
}
